var relationships = ["adoptiveFatherOf", 
            "adoptiveMotherOf", 
            "ancestorOf", 
            "auntOf", 
            "biologicalFatherOf", 
            "biologicalMotherOf", 
            "brotherInLawOf", 
            "brotherOf", 
            "daughterOf", 
            "deathOf", 
            "descendentOf", 
            "fatherInLawOf", 
            "fatherOf", 
            "grandParentOf", 
            "grandfatherOf", 
            "grandmotherOf", 
            "greatGrandParentOf", 
            "greatGrandfatherOf", 
            "greatGrandmotherOf", 
            "hasAdoptiveFather", 
            "hasAdoptiveMother", 
            "hasAncestor", 
            "hasAunt", 
            "hasBiologicalFather", 
            "hasBiologicalMother", 
            "hasBrother", 
            "hasBrotherInLaw", 
            "hasChild", 
            "hasCousin", 
            "hasCousinInLaw", 
            "hasDaughter", 
            "hasDeath", 
            "hasDescendent", 
            "hasDoubleCousin", 
            "hasFather", 
            "hasFatherinLaw", 
            "hasFirstCousin", 
            "hasFirstCousinOnceRemoved", 
            "hasFirstCousinTwiceRemoved", 
            "hasGrandParent", 
            "hasGrandchild", 
            "hasGranddaughter", 
            "hasGrandfather", 
            "hasGrandmother", 
            "hasGrandson", 
            "hasGreatAunt", 
            "hasGreatGrandParent", 
            "hasGreatGrandchild", 
            "hasGreatGrandfather", 
            "hasGreatGrandmother", 
            "hasGreatUncle", 
            "hasHusband", 
            "hasInLaw", 
            "hasMaternalCousin", 
            "hasMother", 
            "hasMotherInLaw", 
            "hasNephew", 
            "hasNiece", 
            "hasParent", 
            "hasPaternalCousin", 
            "hasRelation", 
            "hasSecondCousin", 
            "hasSecondCousinOnceRemoved", 
            "hasSibling", 
            "hasSister", 
            "hasSisterInLaw", 
            "hasSon", 
            "hasSpouse", 
            "hasThirdCousin", 
            "hasUncle", 
            "hasWife", 
            "husbandOf", 
            "isBloodRelationOf", 
            "isChildOf", 
            "isGrandchildOf", 
            "isGranddaughterOf", 
            "isGrandsonOf", 
            "motherInLawOf", 
            "motherOf", 
            "nephewOf", 
            "nieceOf", 
            "parentOf", 
            "sisterInLawOf", 
            "sisterOf", 
            "sonOf", 
            "uncleOf", 
            "wifeOf"];


                $(function() {
                
                
            
             $( "#FamilyRelationships-FamilyRole" ).autocomplete({
                    source: relationships
                    });
                    });
            
            
        
        
